/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppImagePreview: typeof import('./src/components/AppImagePreview.vue')['default']
    BaseSkill: typeof import('./src/components/riic/BaseSkill.vue')['default']
    ImagePreviewContainer: typeof import('./src/components/ImagePreviewContainer.vue')['default']
    ImagePreviewHelpMenu: typeof import('./src/components/ImagePreviewHelpMenu.vue')['default']
    ItemWithCount: typeof import('./src/components/riic/ItemWithCount.vue')['default']
    MonsterSirenAlbumCard: typeof import('./src/components/monsterSiren/MonsterSirenAlbumCard.vue')['default']
    MonsterSirenAlbumDetail: typeof import('./src/components/monsterSiren/MonsterSirenAlbumDetail.vue')['default']
    MonsterSirenAlbumHero: typeof import('./src/components/monsterSiren/MonsterSirenAlbumHero.vue')['default']
    MonsterSirenAlbumsGrid: typeof import('./src/components/monsterSiren/MonsterSirenAlbumsGrid.vue')['default']
    MonsterSirenAlbumsTab: typeof import('./src/components/monsterSiren/MonsterSirenAlbumsTab.vue')['default']
    MonsterSirenPlayer: typeof import('./src/components/monsterSiren/MonsterSirenPlayer.vue')['default']
    MonsterSirenPlayList: typeof import('./src/components/monsterSiren/MonsterSirenPlayList.vue')['default']
    MonsterSirenSongCard: typeof import('./src/components/monsterSiren/MonsterSirenSongCard.vue')['default']
    MonsterSirenSongDetail: typeof import('./src/components/monsterSiren/MonsterSirenSongDetail.vue')['default']
    MonsterSirenSongGrid: typeof import('./src/components/monsterSiren/MonsterSirenSongGrid.vue')['default']
    MonsterSirenSongList: typeof import('./src/components/monsterSiren/MonsterSirenSongList.vue')['default']
    MonsterSirenSongsTab: typeof import('./src/components/monsterSiren/MonsterSirenSongsTab.vue')['default']
    OperatorAvatar: typeof import('./src/components/riic/OperatorAvatar.vue')['default']
    OperatorCard: typeof import('./src/components/riic/OperatorCard.vue')['default']
    RiicSchedule: typeof import('./src/components/riic/RiicSchedule.vue')['default']
    RiicStation: typeof import('./src/components/riic/RiicStation.vue')['default']
    RiicYituliuDecoration: typeof import('./src/components/icons/RiicYituliuDecoration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemePicker: typeof import('./src/components/theme-picker/ThemePicker.vue')['default']
    ThemePickerButton: typeof import('./src/components/theme-picker/ThemePickerButton.vue')['default']
    UAccordion: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
    UColorModeButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UColorPicker: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFieldGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UFileUpload: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UKbd: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    ULink: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/overrides/vue-router/Link.vue')['default']
    UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPage: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageBody: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue')['default']
    UPageHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
    UPagination: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USlider: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
